/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CadastrarClienteRouteImport } from './routes/cadastrar-cliente'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarClienteRoute = CadastrarClienteRouteImport.update({
  id: '/cadastrar-cliente',
  path: '/cadastrar-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/cadastrar-cliente': typeof CadastrarClienteRoute
  '/clientes': typeof ClientesRoute
  '/novo': typeof NovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/cadastrar-cliente': typeof CadastrarClienteRoute
  '/clientes': typeof ClientesRoute
  '/novo': typeof NovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/cadastrar-cliente': typeof CadastrarClienteRoute
  '/clientes': typeof ClientesRoute
  '/novo': typeof NovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alertas' | '/cadastrar-cliente' | '/clientes' | '/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alertas' | '/cadastrar-cliente' | '/clientes' | '/novo'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/cadastrar-cliente'
    | '/clientes'
    | '/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  CadastrarClienteRoute: typeof CadastrarClienteRoute
  ClientesRoute: typeof ClientesRoute
  NovoRoute: typeof NovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-cliente': {
      id: '/cadastrar-cliente'
      path: '/cadastrar-cliente'
      fullPath: '/cadastrar-cliente'
      preLoaderRoute: typeof CadastrarClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  CadastrarClienteRoute: CadastrarClienteRoute,
  ClientesRoute: ClientesRoute,
  NovoRoute: NovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
